### ISSUE TITLE
float considered harmful

### ISSUE THREAD

**Issue by ghost** [angel2d/angel2d#20]
Angel2D uses float for it's floating point data type, for intermediate values, long term storage, and as a conversion medium. Unfortunately, float has significant disadvantages for all of these applications. 

--- Support ---
All platforms that Angel2D supports have hardware support for float and double at roughly the same speed. 
On x86/x64, SSE only supports 4 float's; however, SSE2 supports two double's, and has been available and standard since the Pentium 4.
On ARM (iOS, Android, Windows RT), double is supported on all available platforms, and is as fast as float. Only on new iPhone's with a NEON chip is float substantially faster, and usually only with use of intrinsics.
On PowerPC, the pipeline is designed for double; rounding to single is slower than using double exclusively.

--- Performance ---
On all platforms, long double is at least as big as double (and on linux/mac, is a true extended precision type), and only on PowerPC it is it slower than float or double.
PowerPC uses double double math; this is slightly slower (measurements indicate around 5%).  

--- Hardware ---
On x86/x64, all operations actually occur in long double, internally.
On ARM, all operations occur in their specified type.
On PowerPC, all operations occur on double.

--- Intermediate Values ---
Not all numbers are directly representable in floating points.
If a number cannot be represented, an approximation is used.

Most operations on floating points result in an increase in digits.
ex. 10.5 \* 10.5 = 100.25
If we only had 3 digits to store in, we would store 100.2, with an error of 0.05
Multiplication can lead to twice as many digits as we put in.
Transcendental operations (sin,cos,etc) can be much worse.

By using a larger type than we intend to store in, we keep as many significant figures as possible. Even if we round down at the end, using larger values for intermediates means no loss of significant figures.

Using float for everything means our result can have half as much precision as we started with!

--- Long Term Storage ---
OpenGL does not use doubles, but it often does not use float either; 24 bit floats are still common, and 16 bit "half"s were (and are) often used internally. Using float means inaccurate intermediate values to (possibly) avoid a double to single (or less) conversion to the "sink".

Furthermore, Lua uses double exclusively, and GLFW returns them regularly; many of the libraries do. Using float discards valuable precision from these "sources", resulting in substantially few significant figures to work with.

--- Conversions ---
Angel uses float as if it can safely store and restore an int. It cannot.

Single precision floating points have 24 bits to their significand.
int is 32 bits, 8 less than float can store. 

Converting an int to a float is risky, and causes significant problems.

Double precision floating points have 54 bits in their significand.
They can easily store an int, signed or unsigned.
This is why lua uses double exclusively.

--- Recommended Changes ---
Use double instead of float where ever applicable
Use long double for intermediate values
Change Vector2/3 to use double
Directly use/copy lua values (instead of using userdata) for Vector2/3

--- Possible Alternative ---
Make a two float vector into a standard lua type. This would be possible with either default lua or luaJIT, and make Vector2 a first class Lua object. 
Annotate Vector2 with intrinsics for speed.

--- Conclusions ---
The only reason float could possibly be preferred for use is because it is faster or smaller (and thus faster), but on any platform used by Angel it is not faster, much less safe, and requires large amounts of boilerplate to accommodate (adding f to constants is cumbersome and easy to miss). 

As Angel is based on being understandable instead of performant, uses Lua as it's primary scripting language (which uses double exclusively), and uses C++ as it's main language (which makes all constants double), double should be the preferred type for floating points in Angel.

**Comment by sjackso** [comment]
I can think of one additional good reason to use 32-bit float for world coordinates: it's the native data type for Box2d.  Changing to doubles (which may well be a good idea for all the reasons you have given) would introduce some new type conversions at the Angel2d / Box2d boundary, and could lead to unexpected behavior when interacting with world coordinates.

Naturally, this is one for @sjml to weigh in on.  Will floats still be the chief currency of Angel2d V4?

**Comment by ghost** [comment]
Down conversions are harmful; upconversions are not.

Box2D does indeed use float (because I think it can benefit from SSE), but Lua and most of the other sources use double. Generally, you want precision to "flow" from sources, to sinks, at as high a precision (and as bounded a precision) as possible.

Think of it like this: precision flows from lua, and currently is hard cutted going into Angel, then flows to Box2D. To keep as much precision as long as possible, you'd want to get rid of that hard cut. Box2D is going to take float no matter what we do, but the rest of Angel would benefit from having double.

**Comment by sjml** [comment]
Long story short: we're not going to be making this change. 32-bit floats are still standard across the games industry for a variety of reasons, most of which involve performance and memory reasons, but ultimately they are adequate precision for the overwhelming majority of game contexts -- in places where they are not sufficient, we'll use doubles under the hood, but we'll continue using standard floats for most interfaces. 

If there's a demonstrable problem that you're seeing from Angel's use of float, definitely file a specific bug related to that, but on a broad basis, this isn't a change that's worth the effort.

**Comment by ghost** [comment]
Lua is the de facto standard scripting engine for games; it uses doubles.
As indicated, unless you use SSE there is no performance reason, and given you use Lua, your conversions are actually slowing it down (measured performance in Angel2D with double's rather than float's is higher, not lower, for this reason).

Standard practice is to use a typdef, such as is seen in OGRE.

I'm not sure what standard you are referring to; is there perhaps a document you can link me to, because in Source, Ogre, and many other projects there are careful rules for when to use float and when to use double; if Angel has such rules, they seem ill followed internally.
