### ISSUE TITLE
How can I create Game Manager?

### ISSUE THREAD

**Issue by erayaydin** [angel2d/angel2d#24]
Hello,
I want use

```
theWorld.SetGameManager(???);
```

How can I create a Game Manager. I think I must create gameManagerGame.h and gameManagerGame.cpp. Whats I write into to gameManagerGame.h and gameManagerGame.cpp. Any example? I can't understand at IntroGame folder.

**Comment by sjml** [comment]
You want to create a class that inherits from GameManager. IntroGame or one of the games from the demo pack contain examples.

**Comment by erayaydin** [comment]
Can u make a example game manager(lightweight). I can't understand DemoGameManager and game demo pack header files.

**Comment by sjml** [comment]
Check out the demo pack on angel2d.com; it has several examples.
