### ISSUE TITLE
Angel2D won't find GLFW

### ISSUE THREAD

**Issue by vitto** [angel2d/angel2d#28]
I'm doing my first steps with `C++` and game development to build a simple prototype.

This would be more as a question because i'm not sure is an issue.

I've chosen [Angel2D](http://angel2d.com) as framework to get some help from the beginning but I have problems to get it working with a simple `Hello world!` console message.

I've followed the [installation instructions for Mac](https://code.google.com/p/angel-engine/#Mac) but it won't work properly.

My project structure is

```
/GamePrototype/test.cpp // the file I try to build
/GamePrototype/Angel    // Angel2D is inside this folder
/GamePrototype/Etc
```

If I try a file like this:

```
#include <iostream>
using namespace std;

int main() {
    cout << "Hello world!" << endl;
    return 0;
 }
```

Sublime Text opens it's console and shows `Hello world!` correctly.

If I just include Angel main file `Angel.h` to the file like this

```
#include "Angel/Angel.h"
#include <iostream>
using namespace std;

int main() {
    cout << "Hello world!" << endl;
    return 0;
}
```

It throws this error:

```
/Angel/Actors/../Infrastructure/../Util/../Infrastructure/Common.h:94:11:
fatal error: 'GLFW/glfw3.h' file not found
    #include <GLFW/glfw3.h>
                  ^
```

The file is probably located in `/GamePrototype/Angel/Libraries/glfw-3.0.3/include/GLFW/glfw3.h`

Probably it's just a base knowledge of `C++` and how to build projects, what's wrong with the [OpenGL](http://www.glfw.org) library?

It seems like it's just trying to load the library in the wrong place, but I can't believe the release is broken.

**Comment by sjml** [comment]
Use the available Xcode project to build your game -- it has all the paths set up and ready to go.

**Comment by vitto** [comment]
With Xcode 6.1 builds seems to not working, now i get this error:

`No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=i386).`

But this is easy to be fixed by changing the project settings, for what I read online it seems to be a problem introduced by Apple.

I also get some different errors:

```
PhaseScriptExecution Generate\ Lua\ Wrapping /Users/.../Library/Developer/Xcode/DerivedData/IntroGame-gtsvpnlldngoffgzlulaosvkiidb/Build/Intermediates/IntroGame.build/Debug/IntroGame.build/Script-34388F3B11E3EF61002A79B1.sh
    cd /Users/.../GameDev/Pipiloca/IntroGame
    /bin/sh -c /Users/.../Library/Developer/Xcode/DerivedData/IntroGame-gtsvpnlldngoffgzlulaosvkiidb/Build/Intermediates/IntroGame.build/Debug/IntroGame.build/Script-34388F3B11E3EF61002A79B1.sh

ERROR: swig version 3.0.2 is too old for Angel; update to at least 2.0.6.
Command /bin/sh failed with exit code 1
```
