### ISSUE TITLE
Message::GetMessageType 

### ISSUE THREAD

**Issue by MrSnowman** [angel2d/angel2d#38]
In Message.h
///A templated class for delivering additional information with Messages
/*\* 
- This class lets you define your own message types that carry data with 
-  them. For instance, if you wanted to create a Message that carried 
-  a world location with it: 
- 
- \code
- TypedMessage<Vector2> *m = new TypedMessage<Vector2>("SomethingHappenedHere", Vector2(-3, -2));
- \endcode
- 
- This gets sent through the Switchboard as just a pointer to the base class,
-  though, so your MessageReceivers will have to parse what it is from the
-  Message::GetMessageType function and cast it appropriately from there. 
  */

The Message::GetMessageType function isn't implemented or declared anywhere it seems. Maybe I'm missing something.

**Comment by sjml** [comment]
It was changed to "GetMessageName," but the docs weren't updated. :)
