### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by eray-z** [angel2d/angel2d#39]
Hi angel2d developer team.

I very like your framework and I want to write own game engine.  I was looking  classes of the engine and your codes looks like very clean. I can understand how the engine works. I know It's not easy and the project is amazing.

I hope you still update the engine? And do you think to add android option in the future?

Thank you.

**Comment by aleksandaratanasov** [comment]
I really doubt it. Alone the fact that code hasn't been updated in 3 years and there are unmerged pull requests from others some of which 2 years old or so indicates that the project is dead. I recommend you look at Godot which also offers Android support or somewhere else.

**Comment by eray-z** [comment]
Sad news. : ( I'm finding a library just like angel2d. Do you know any alternative?

**Comment by sjml** [comment]
Hi there! Yes, sadly, the project has more or less died out. It doesn't fit the style or technology needs of games I tend to make anymore, so I haven't really needed to update it. I'm not even sure where to point you for alternatives these days. I'm told Unity has pretty good 2d capabilities...

Sorry we can't provide what you need!

**Comment by aleksandaratanasov** [comment]
@eray-z As I've mentioned check out Godot. They also plan on adding support for a couple of programming languages. Android support is there.

**Comment by eray-z** [comment]
@aleksandaratanasov  Thanks but I'm finding a little part of game engine to write own game engine. Godot is focusing gdscript. I'm using cocos2d-x for now, it's not bad. But I want to use own simple-2d-lite game engine in the future. Because I never use too many features of cocos2d-x. 

@sjml yep, angel2d is like a basic prototype of a game engine to write own game engine. Most of people don't need to that like me.

For example, löve2d is a simple game engine. I wish there was a smilar alternative for c++.

**Comment by aleksandaratanasov** [comment]
@eray-z They are planning on adding support for C++, Mono etc. The engine itself is written in C++ AND can be extended using C++. For performance critical components in the game it is advised to go for C++.
