### ISSUE TITLE
can't open in-game console

### ISSUE THREAD

**Issue by progsource** [angel2d/angel2d#5]
Hi,

I have a different keyboard layout (german). Probably that is also the main reason, why I can't open the in-game console. It would be very helpful if the key to open the console was configurable.

(ubuntu build)

**Comment by sjml** [comment]
Agreed, this would be nice. Will try to get this in the next build. In the meanwhile, you can customize it pretty easily by altering the code for GetToggleConsoleKey in Console.h.

**Comment by sjml** [comment]
This is now configurable in Angel4. Even though it's still in development, I'm going to close this for now so it can be clear what still needs to be done. :)
